apiVersion: v1
kind: Service
metadata:
  name: {{ include "byoa2023.fullname" . }}
  labels:
    {{- include "byoa2023.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "byoa2023.selectorLabels" . | nindent 4 }}
